import { motion, useInView, useScroll, useTransform, useMotionValue, animate } from "framer-motion";
import { useRef, useEffect, useState } from "react";
import { useLanguage } from "@/contexts/LanguageContext";
import { useNavigate } from "react-router-dom";

// LYNT — founder spotlight, Apple-keynote style.
// Content sourced from JapanPath_CaseStudy_v2.pdf.

const pillars = [
  {
    kicker: "01 — The Problem",
    kickerJa: "01 — 課題",
    title: "Moving to Japan is a 40–60 hour research tax.",
    titleJa: "日本への移住は40〜60時間の調査負担。",
    body:
      "20+ disconnected sources — JASSO, Immigration Bureau, MyNavi, LinkedIn, embassy PDFs, Reddit. Conflicting advice, zero personalization. Western CVs get silently rejected because Japanese employers expect a JIS-compliant Rirekisho with photo, furigana and wareki (Reiwa/Heisei) dates. 30+ visa categories with country-specific gating, and one wrong assumption can void a job offer.",
    bodyJa:
      "JASSO・入管・マイナビ・LinkedIn・大使館PDF・Redditなど20以上の情報源が分散し、矛盾した助言とゼロのパーソナライズ。日本企業は写真・ふりがな・和暦（令和・平成）入りのJIS準拠履歴書を求めるため、欧米CVは静かに不採用に。30以上のビザ類型と国別の要件、ひとつの誤解で内定が無効に。",
    stat: "40–60h → 1 session",
    statJa: "40〜60h → 1セッション",
  },
  {
    kicker: "02 — The Product",
    kickerJa: "02 — プロダクト",
    title: "One cockpit. Onboarding → visa → resume → offer.",
    titleJa: "ひとつのコックピット。オンボーディングからビザ・履歴書・内定まで。",
    body:
      "LYNT is a production-grade, bilingual (EN/JP) decision & execution platform: 14+ branching onboarding routes, a 0–100 Readiness Score across 6 dimensions, JIS B5/A4 Rirekisho + Shokumukirekisho + Soufujou cover-letter builder, a 30+ visa intelligence engine with country/age/income gating, an AI Resume Suite (Polish · ATS Review · JD Tailor · Cover Letter), Cost-of-Living comparator across 5 cities, and a curated portal of visa-sponsoring employers.",
    bodyJa:
      "LYNTは本番品質のバイリンガル（EN/JP）意思決定・実行プラットフォーム。14以上の分岐型オンボーディング、6軸の0–100レディネススコア、JIS B5/A4の履歴書・職務経歴書・送付状ビルダー、30以上のビザ判定エンジン（国・年齢・収入対応）、AI履歴書スイート（添削・ATSレビュー・JD最適化・送付状）、5都市の生活費試算、ビザスポンサー求人ポータル。",
    stat: "20+ production screens",
    statJa: "本番画面 20以上",
  },
  {
    kicker: "03 — The Craft",
    kickerJa: "03 — 設計",
    title: "Japanese minimalism. Linear-grade polish.",
    titleJa: "日本的ミニマリズム × Linear級の磨き込み。",
    body:
      "Vermillion shuiro (#E94E1B) over Sumi slate (#1F2937). Inter for Latin, Noto Sans JP for kana/kanji. Token-only theming — zero hardcoded colors across 80+ components, instant dark-mode swap. Every list collapses to a card stack below 640px, every async route uses skeleton loaders (not spinners), every destructive action requires confirmation. The Rirekisho preview is pixel-accurate to printed JIS B5 — photo box, furigana row, wareki column — so candidates trust what they send.",
    bodyJa:
      "墨色のスレートに朱色（朱色 #E94E1B / スレート #1F2937）。LatinはInter、仮名・漢字はNoto Sans JP。トークン専用テーマ — 80以上のコンポーネントでハードコード色ゼロ、ダークモードへ瞬時切替。640px以下では全リストがカードに、非同期ルートはスピナーではなくスケルトン、破壊操作には必ず確認。履歴書プレビューは写真欄・ふりがな・年号列までJIS B5の印刷物にピクセル一致。",
    stat: "Lighthouse 92 / 98 / 100 / 100",
    statJa: "Lighthouse 92 / 98 / 100 / 100",
  },
  {
    kicker: "04 — The Engine",
    kickerJa: "04 — エンジン",
    title: "RLS-safe. Edge-served. AI-constrained.",
    titleJa: "RLSで安全、エッジで配信、AIは構造化。",
    body:
      "React 18 + Vite 5 + strict TypeScript (zero any in the resume engine, autogenerated Supabase types). Supabase Postgres with Row Level Security on every public table, GRANTs paired with every CREATE TABLE, roles isolated in a separate user_roles table behind a has_role() SECURITY DEFINER function. Two Deno Edge Functions pipe Gemini 2.5 Flash through Lovable AI Gateway with strict JSON output — no API key ever touches the client. Initial JS bundle stays under 220 KB gzipped, TTI under 1.5s on mid-range Android.",
    bodyJa:
      "React 18 + Vite 5 + strict TypeScript（履歴書エンジンに any ゼロ、Supabase型は自動生成）。Supabase Postgresは全公開テーブルにRLS、CREATE TABLEごとにGRANT併記、rolesはhas_role() SECURITY DEFINER越しの専用テーブルに分離。Deno Edge Functionが2本、Lovable AI Gateway越しにGemini 2.5 FlashへJSON厳格モードでアクセス — APIキーはクライアントに露出させない。初期JSは220KB gzip以下、ミドルレンジAndroidでTTI 1.5秒以下。",
    stat: "<220 KB · TTI <1.5s · 6 tables · 100% RLS",
    statJa: "<220KB · TTI<1.5s · 6テーブル · RLS 100%",
  },
];

const metrics = [
  { value: "14", suffix: "+", label: "Onboarding routes", labelJa: "オンボーディング経路" },
  { value: "30", suffix: "+", label: "Visa types modeled", labelJa: "ビザ類型を網羅" },
  { value: "20", suffix: "+", label: "Production screens", labelJa: "本番画面" },
  { value: "100", suffix: "", label: "0 → 100 Readiness Score", labelJa: "0→100 レディネススコア" },
  { value: "9.5", suffix: "k", label: "Lines of TypeScript", labelJa: "TypeScript行数" },
  { value: "6", suffix: "", label: "Postgres tables · 100% RLS", labelJa: "Postgresテーブル · RLS 100%" },
  { value: "220", suffix: "KB", label: "Initial JS (gz)", labelJa: "初期JS（gzip）" },
  { value: "1.5", suffix: "s", label: "TTI (mid-Android)", labelJa: "TTI（中位Android）" },
];

const featureGrid = [
  { n: "01", t: "Personalized Onboarding", d: "14+ branching routes that rewrite questions based on goal & stage.", tJa: "パーソナライズドオンボーディング", dJa: "目標・状況で質問が動的に書き換わる14+の分岐ルート。" },
  { n: "02", t: "Readiness Score 0–100", d: "Composite across JLPT · finance · documents · skills · timeline · visa fit.", tJa: "レディネススコア 0–100", dJa: "JLPT・資金・書類・スキル・時期・ビザ適合の6軸合成。" },
  { n: "03", t: "JIS Rirekisho Builder", d: "Pixel-accurate B5/A4 with auto wareki conversion and print-perfect CSS.", tJa: "JIS履歴書ビルダー", dJa: "B5/A4ピクセル一致、和暦自動変換、印刷完璧CSS。" },
  { n: "04", t: "Visa Intelligence", d: "30+ types · HSP points calculator · country/age/income gating.", tJa: "ビザ・インテリジェンス", dJa: "30以上の類型・HSP点数計算・国/年齢/収入ゲーティング。" },
  { n: "05", t: "AI Resume Suite", d: "Polish · ATS review (0–100 + keigo) · JD tailor · cover letter.", tJa: "AI履歴書スイート", dJa: "添削・ATSレビュー（0–100＋敬語）・JD最適化・送付状。" },
  { n: "06", t: "Decision Engine", d: "Side-by-side path comparison weighted by cost, time, success probability.", tJa: "意思決定エンジン", dJa: "コスト・時間・成功率で重み付けされた進路比較。" },
];

const failures = [
  { x: "Three.js mascot tank", y: "Replaced with SVG + Framer Motion — saved ~180 KB.", xJa: "Three.jsマスコットが重い", yJa: "SVG＋Framer Motionに置換、約180KB削減。" },
  { x: "Standalone gamification module", y: "Folded into Mission Mode tied to Readiness Score.", xJa: "独立ゲーミフィケーション", yJa: "Mission Modeに統合しレディネスと連動。" },
  { x: "Generic split-card auth", y: "Redesigned with Vermillion/Slate identity, furigana hints, single-column mobile.", xJa: "汎用的な認証画面", yJa: "朱色/墨色のID、ふりがな、モバイル単列で再設計。" },
  { x: "Roles on the profiles table", y: "Moved to user_roles + has_role() SECURITY DEFINER (no priv-esc).", xJa: "rolesをprofilesに保存", yJa: "user_roles＋has_role() SECURITY DEFINERへ移行。" },
];

// Animated counter ------------------------------------------------------------
const Counter = ({ to }: { to: string }) => {
  const mv = useMotionValue(0);
  const [display, setDisplay] = useState("0");
  const ref = useRef<HTMLSpanElement>(null);
  const inView = useInView(ref, { once: true, margin: "-50px" });
  const target = parseFloat(to);
  const decimals = (to.split(".")[1] || "").length;

  useEffect(() => {
    if (!inView) return;
    const controls = animate(mv, target, {
      duration: 1.6,
      ease: [0.22, 1, 0.36, 1],
      onUpdate: (v) => setDisplay(v.toFixed(decimals)),
    });
    return controls.stop;
  }, [inView, target, decimals, mv]);

  return <span ref={ref}>{display}</span>;
};

// Pillar block ----------------------------------------------------------------
const Pillar = ({ p, language }: { p: (typeof pillars)[0]; language: "en" | "ja" }) => {
  const ref = useRef(null);
  const inView = useInView(ref, { once: true, margin: "-150px" });
  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: 60 }}
      animate={inView ? { opacity: 1, y: 0 } : { opacity: 0, y: 60 }}
      transition={{ duration: 0.9, ease: [0.22, 1, 0.36, 1] }}
      className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-16 items-start"
    >
      <div className="lg:col-span-4 lg:sticky lg:top-32">
        <div className="text-xs tracking-[0.3em] uppercase text-background/50">
          {language === "ja" ? p.kickerJa : p.kicker}
        </div>
        <motion.div
          initial={{ scaleX: 0 }}
          animate={inView ? { scaleX: 1 } : { scaleX: 0 }}
          transition={{ duration: 0.8, delay: 0.2 }}
          style={{ transformOrigin: "left" }}
          className="mt-6 h-px w-24 bg-background/60"
        />
        <div className="mt-6 inline-flex items-center gap-2 text-[11px] tracking-[0.25em] uppercase text-background/70 border border-background/20 rounded-full px-3 py-1.5 tabular-nums">
          <span className="w-1.5 h-1.5 rounded-full bg-background animate-pulse" />
          {language === "ja" ? p.statJa : p.stat}
        </div>
      </div>
      <div className="lg:col-span-8">
        <h3 className="text-3xl sm:text-5xl lg:text-[3.75rem] font-bold tracking-[-0.04em] leading-[1.02]">
          {language === "ja" ? p.titleJa : p.title}
        </h3>
        <p className="mt-6 sm:mt-8 text-base sm:text-lg lg:text-xl text-background/70 leading-relaxed max-w-2xl">
          {language === "ja" ? p.bodyJa : p.body}
        </p>
      </div>
    </motion.div>
  );
};

// Main section ----------------------------------------------------------------
const LyntSection = () => {
  const { language } = useLanguage();
  const navigate = useNavigate();
  const sectionRef = useRef<HTMLDivElement>(null);
  const headerRef = useRef<HTMLDivElement>(null);
  const isHeaderInView = useInView(headerRef, { once: true, margin: "-100px" });

  const { scrollYProgress } = useScroll({
    target: sectionRef,
    offset: ["start end", "end start"],
  });
  const bgY = useTransform(scrollYProgress, [0, 1], ["-10%", "10%"]);
  const wordmarkScale = useTransform(scrollYProgress, [0, 0.4], [0.92, 1]);
  const marqueeX = useTransform(scrollYProgress, [0, 1], ["0%", "-40%"]);

  return (
    <section
      ref={sectionRef}
      id="lynt"
      aria-label="LYNT — Founder spotlight"
      className="relative overflow-hidden bg-foreground text-background"
    >
      {/* Atmospheric backdrop — aurora + grid + edge hairlines */}
      <motion.div
        aria-hidden
        style={{ y: bgY }}
        className="pointer-events-none absolute inset-0"
      >
        <div
          className="absolute inset-0 opacity-[0.10]"
          style={{
            backgroundImage:
              "radial-gradient(60% 50% at 18% 12%, hsl(var(--background)) 0%, transparent 60%), radial-gradient(50% 45% at 88% 88%, hsl(var(--background)) 0%, transparent 65%)",
          }}
        />
        <div
          className="absolute inset-0 opacity-[0.05]"
          style={{
            backgroundImage:
              "linear-gradient(hsl(var(--background)/0.5) 1px, transparent 1px), linear-gradient(90deg, hsl(var(--background)/0.5) 1px, transparent 1px)",
            backgroundSize: "96px 96px",
            maskImage:
              "radial-gradient(ellipse at center, black 40%, transparent 80%)",
            WebkitMaskImage:
              "radial-gradient(ellipse at center, black 40%, transparent 80%)",
          }}
        />
        <div
          className="absolute inset-x-0 top-0 h-px"
          style={{ background: "linear-gradient(90deg, transparent, hsl(var(--background)/0.35), transparent)" }}
        />
        <div
          className="absolute inset-x-0 bottom-0 h-px"
          style={{ background: "linear-gradient(90deg, transparent, hsl(var(--background)/0.25), transparent)" }}
        />
      </motion.div>

      <div className="relative container mx-auto px-4 sm:px-6 lg:px-12 py-24 sm:py-32 lg:py-40">
        {/* Top meta strip */}
        <motion.div
          ref={headerRef}
          initial={{ opacity: 0, y: 20 }}
          animate={isHeaderInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
          transition={{ duration: 0.6 }}
          className="flex items-center justify-between gap-6 text-[11px] tracking-[0.3em] uppercase"
        >
          <div className="flex items-center gap-3 text-background/70">
            <span className="h-px w-10 bg-background/40" />
            {language === "ja" ? "創業プロダクト" : "Founder Product"}
            <span className="opacity-40">·</span>
            {language === "ja" ? "ケーススタディ v2" : "Case Study v2"}
          </div>
          <div className="hidden sm:inline-flex items-center gap-2 rounded-full border border-background/15 bg-background/[0.04] backdrop-blur-md px-3 py-1.5 text-background/80">
            <span className="relative flex h-1.5 w-1.5">
              <span className="absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-60 animate-ping" />
              <span className="relative inline-flex h-1.5 w-1.5 rounded-full bg-emerald-400" />
            </span>
            {language === "ja" ? "稼働中 — プレビュー" : "Live — Preview"}
          </div>
        </motion.div>

        {/* Wordmark with gradient sheen + shimmer */}
        <motion.h2
          style={{ scale: wordmarkScale }}
          initial={{ opacity: 0, y: 40 }}
          animate={isHeaderInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 40 }}
          transition={{ duration: 0.9, ease: [0.22, 1, 0.36, 1] }}
          className="mt-10 font-bold tracking-[-0.06em] leading-[0.85] text-[18vw] sm:text-[16vw] lg:text-[13vw] relative overflow-hidden"
        >
          <span
            className="bg-clip-text text-transparent"
            style={{
              backgroundImage:
                "linear-gradient(180deg, hsl(var(--background)) 0%, hsl(var(--background)/0.78) 60%, hsl(var(--background)/0.55) 100%)",
            }}
          >
            LYNT
          </span>
          <span className="text-background/35">.</span>
          <motion.span
            aria-hidden
            initial={{ x: "-120%" }}
            animate={{ x: "220%" }}
            transition={{ duration: 6, repeat: Infinity, ease: "linear", repeatDelay: 1.5 }}
            className="pointer-events-none absolute inset-y-0 w-1/3 mix-blend-overlay"
            style={{
              background:
                "linear-gradient(90deg, transparent, hsl(var(--background)/0.55), transparent)",
              filter: "blur(20px)",
            }}
          />
        </motion.h2>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={isHeaderInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
          transition={{ duration: 0.8, delay: 0.2 }}
          className="mt-10 sm:mt-14 grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-10 items-end"
        >
          <p className="lg:col-span-8 max-w-3xl text-xl sm:text-2xl lg:text-[2rem] tracking-[-0.02em] leading-[1.2] text-background/90">
            {language === "ja"
              ? "日本での留学・就職・移住のためのOS。創業から設計、フルスタック実装、AI連携まで一人で構築。"
              : "The operating system for studying, working & relocating to Japan. Founded, designed and engineered end-to-end — solo."}
          </p>
          {/* Premium glass meta card */}
          <div className="lg:col-span-4">
            <div className="relative rounded-2xl border border-background/15 bg-background/[0.04] backdrop-blur-md p-5 overflow-hidden">
              <div
                aria-hidden
                className="absolute inset-x-0 -top-px h-px"
                style={{ background: "linear-gradient(90deg, transparent, hsl(var(--background)/0.5), transparent)" }}
              />
              <div className="flex items-center justify-between text-[10px] tracking-[0.28em] uppercase text-background/50">
                <span>{language === "ja" ? "創業 · 単独構築" : "Founder · Solo build"}</span>
                <span className="font-mono">v2.0</span>
              </div>
              <div className="mt-4 grid grid-cols-2 gap-3 text-sm">
                <div>
                  <div className="text-background/40 text-[10px] tracking-[0.22em] uppercase">{language === "ja" ? "役割" : "Role"}</div>
                  <div className="mt-1 text-background/90">B.Tech CSE · 2026{language === "ja" ? "新卒" : " grad"}</div>
                </div>
                <div>
                  <div className="text-background/40 text-[10px] tracking-[0.22em] uppercase">{language === "ja" ? "対象面" : "Surface"}</div>
                  <div className="mt-1 text-background/90">Web · iOS-class polish</div>
                </div>
                <div className="col-span-2">
                  <div className="text-background/40 text-[10px] tracking-[0.22em] uppercase">Stack</div>
                  <div className="mt-1 text-background/90 leading-snug">React · TS · Supabase · Gemini · Framer</div>
                </div>
              </div>
            </div>
          </div>
        </motion.div>

        {/* Keynote-style product surface */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-120px" }}
          transition={{ duration: 0.9, ease: [0.22, 1, 0.36, 1] }}
          className="mt-16 sm:mt-20"
        >
          <div className="relative rounded-[28px] border border-background/15 bg-background/[0.03] backdrop-blur-xl overflow-hidden shadow-[0_40px_120px_-40px_rgba(0,0,0,0.6)]">
            <div
              aria-hidden
              className="pointer-events-none absolute -inset-px rounded-[28px]"
              style={{
                background:
                  "radial-gradient(80% 60% at 50% 0%, hsl(var(--background)/0.12), transparent 60%)",
              }}
            />
            <div className="flex items-center justify-between px-5 sm:px-7 py-3 border-b border-background/10 bg-background/[0.04]">
              <div className="flex items-center gap-2">
                <span className="w-2.5 h-2.5 rounded-full bg-background/30" />
                <span className="w-2.5 h-2.5 rounded-full bg-background/30" />
                <span className="w-2.5 h-2.5 rounded-full bg-background/30" />
              </div>
              <div className="text-[10px] sm:text-xs tracking-[0.3em] uppercase text-background/55 font-mono">
                lynt.app  ·  /onboarding
              </div>
              <div className="hidden sm:block text-[10px] text-background/40 font-mono tabular-nums">EN ⁄ 日本語</div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-12 gap-6 p-6 sm:p-10">
              <div className="md:col-span-7">
                <div className="text-[10px] tracking-[0.3em] uppercase text-background/55">
                  {language === "ja" ? "レディネススコア" : "Readiness Score"}
                </div>
                <div className="mt-3 flex items-baseline gap-3">
                  <div className="text-6xl sm:text-7xl font-bold tracking-[-0.04em] tabular-nums">
                    <Counter to="82" />
                  </div>
                  <div className="text-background/55 text-sm">/ 100</div>
                </div>
                <div className="mt-5 h-1.5 w-full rounded-full bg-background/10 overflow-hidden">
                  <motion.div
                    initial={{ width: 0 }}
                    whileInView={{ width: "82%" }}
                    viewport={{ once: true }}
                    transition={{ duration: 1.4, ease: [0.22, 1, 0.36, 1], delay: 0.2 }}
                    className="h-full rounded-full"
                    style={{
                      background:
                        "linear-gradient(90deg, hsl(var(--background)/0.95), hsl(var(--background)/0.55))",
                    }}
                  />
                </div>
                <div className="mt-6 grid grid-cols-3 gap-2 text-[10px] tracking-[0.22em] uppercase text-background/60">
                  {["JLPT N3", "Visa · HSP", "Docs 6/6"].map((c) => (
                    <span key={c} className="rounded-full border border-background/15 px-3 py-1.5 text-center">
                      {c}
                    </span>
                  ))}
                </div>
              </div>
              <div className="md:col-span-5 grid grid-cols-2 gap-3">
                {[
                  { k: language === "ja" ? "履歴書" : "Rirekisho", v: "JIS B5", t: language === "ja" ? "完成" : "Ready" },
                  { k: language === "ja" ? "ビザ" : "Visa Path", v: "Engineer", t: language === "ja" ? "適格" : "Eligible" },
                  { k: language === "ja" ? "送付状" : "Cover Letter", v: "Soufujou", t: language === "ja" ? "下書済" : "Drafted" },
                  { k: language === "ja" ? "月額生活費" : "Cost / mo", v: "¥168k", t: "Tokyo" },
                ].map((card) => (
                  <div
                    key={card.k}
                    className="rounded-2xl border border-background/15 bg-background/[0.04] p-4 hover:bg-background/[0.07] transition-colors duration-300"
                  >
                    <div className="text-[10px] tracking-[0.22em] uppercase text-background/45">
                      {card.k}
                    </div>
                    <div className="mt-2 text-lg font-semibold tracking-tight">{card.v}</div>
                    <div className="mt-1 text-[11px] text-emerald-300/85">● {card.t}</div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </motion.div>

        {/* Metrics rail */}
        <div className="mt-20 sm:mt-28">
          <div className="text-[11px] tracking-[0.3em] uppercase text-background/55 mb-6">
            {language === "ja" ? "数字で見るLYNT" : "By the numbers"}
          </div>
          <div className="rounded-3xl border border-background/15 overflow-hidden bg-background/[0.02] backdrop-blur-sm">
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-px bg-background/10">
              {metrics.map((m, i) => (
                <motion.div
                  key={m.label}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, margin: "-50px" }}
                  transition={{ duration: 0.5, delay: i * 0.06 }}
                  className="relative bg-foreground p-6 sm:p-8 group overflow-hidden"
                >
                  <div
                    aria-hidden
                    className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-500"
                    style={{
                      background:
                        "radial-gradient(80% 60% at 50% 0%, hsl(var(--background)/0.08), transparent 60%)",
                    }}
                  />
                  <div className="relative text-3xl sm:text-5xl font-bold tracking-[-0.04em] tabular-nums flex items-baseline">
                    <Counter to={m.value} />
                    <span className="text-background/60 text-2xl sm:text-3xl ml-1">
                      {m.suffix}
                    </span>
                  </div>
                  <div className="relative mt-2 text-[10px] sm:text-xs uppercase tracking-[0.22em] text-background/55">
                    {language === "ja" ? m.labelJa : m.label}
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </div>

        {/* Marquee impact strip with edge fades */}
        <div className="mt-14 relative overflow-hidden py-6">
          <div
            aria-hidden
            className="pointer-events-none absolute inset-y-0 left-0 w-24 z-10"
            style={{ background: "linear-gradient(90deg, hsl(var(--foreground)), transparent)" }}
          />
          <div
            aria-hidden
            className="pointer-events-none absolute inset-y-0 right-0 w-24 z-10"
            style={{ background: "linear-gradient(-90deg, hsl(var(--foreground)), transparent)" }}
          />
          <motion.div
            style={{ x: marqueeX }}
            className="flex gap-12 whitespace-nowrap text-sm sm:text-base tracking-[0.15em] uppercase text-background/55"
          >
            {Array.from({ length: 2 }).map((_, k) => (
              <div key={k} className="flex gap-12">
                <span>Lighthouse 92 · 98 · 100 · 100</span>
                <span className="opacity-30">◆</span>
                <span>JIS-compliant Rirekisho</span>
                <span className="opacity-30">◆</span>
                <span>6 RLS-protected tables</span>
                <span className="opacity-30">◆</span>
                <span>2 Edge Functions</span>
                <span className="opacity-30">◆</span>
                <span>Gemini 2.5 Flash via AI Gateway</span>
                <span className="opacity-30">◆</span>
                <span>4 resume templates · B5 / A4 / Soufujou</span>
                <span className="opacity-30">◆</span>
              </div>
            ))}
          </motion.div>
        </div>


        {/* Pillars — Apple-keynote chapters */}
        <div className="mt-24 sm:mt-32 space-y-32 sm:space-y-48">
          {pillars.map((p) => (
            <Pillar key={p.kicker} p={p} language={language} />
          ))}
        </div>

        {/* Feature grid */}
        <div className="mt-32 sm:mt-40">
          <div className="flex items-end justify-between gap-6 mb-12">
            <div>
              <div className="text-xs tracking-[0.3em] uppercase text-background/55">
                {language === "ja" ? "主要機能 — 抜粋" : "Key Features — Selected"}
              </div>
              <h3 className="mt-4 text-3xl sm:text-5xl font-bold tracking-[-0.03em]">
                {language === "ja" ? "12機能のうち6つ。" : "Six of twelve."}
              </h3>
            </div>
            <div className="hidden sm:block text-sm text-background/55 tabular-nums font-mono">06 / 12</div>
          </div>
          <div className="rounded-3xl border border-background/15 overflow-hidden bg-background/[0.02] backdrop-blur-sm">
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-px bg-background/10">
              {featureGrid.map((f, i) => (
                <motion.div
                  key={f.n}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, margin: "-50px" }}
                  transition={{ duration: 0.5, delay: i * 0.05 }}
                  className="relative bg-foreground p-7 sm:p-9 group overflow-hidden"
                >
                  <div
                    aria-hidden
                    className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-500"
                    style={{
                      background:
                        "radial-gradient(80% 60% at 50% 0%, hsl(var(--background)/0.08), transparent 60%)",
                    }}
                  />
                  <div className="relative text-xs tracking-[0.3em] text-background/45 font-mono">
                    {f.n}
                  </div>
                  <div className="relative mt-4 text-xl font-semibold tracking-tight">
                    {language === "ja" ? f.tJa : f.t}
                  </div>
                  <p className="relative mt-3 text-sm text-background/65 leading-relaxed">
                    {language === "ja" ? f.dJa : f.d}
                  </p>
                </motion.div>
              ))}
            </div>
          </div>
        </div>


        {/* What failed */}
        <div className="mt-32 sm:mt-40">
          <div className="text-xs tracking-[0.3em] uppercase text-background/50">
            {language === "ja" ? "失敗と是正" : "What Failed · How It Was Fixed"}
          </div>
          <h3 className="mt-4 text-3xl sm:text-5xl font-bold tracking-[-0.03em]">
            {language === "ja" ? "削った決断。" : "Decisions that got cut."}
          </h3>
          <div className="mt-10 divide-y divide-background/10 border-y border-background/10">
            {failures.map((f, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, x: -20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true, margin: "-50px" }}
                transition={{ duration: 0.5, delay: i * 0.06 }}
                className="grid grid-cols-1 md:grid-cols-12 gap-4 md:gap-8 py-6"
              >
                <div className="md:col-span-1 text-sm font-mono text-background/40 tabular-nums">
                  ✕ 0{i + 1}
                </div>
                <div className="md:col-span-5 text-lg font-medium tracking-tight">
                  {language === "ja" ? f.xJa : f.x}
                </div>
                <div className="md:col-span-6 text-sm text-background/60 leading-relaxed">
                  → {language === "ja" ? f.yJa : f.y}
                </div>
              </motion.div>
            ))}
          </div>
        </div>

        {/* CTA */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.7 }}
          className="mt-32 sm:mt-40 relative"
        >
          <div className="relative rounded-3xl border border-background/15 bg-background/[0.03] backdrop-blur-xl overflow-hidden p-8 sm:p-12">
            <div
              aria-hidden
              className="pointer-events-none absolute inset-0"
              style={{
                background:
                  "radial-gradient(60% 80% at 20% 0%, hsl(var(--background)/0.10), transparent 60%), radial-gradient(50% 80% at 100% 100%, hsl(var(--background)/0.08), transparent 60%)",
              }}
            />
            <div
              aria-hidden
              className="absolute inset-x-0 -top-px h-px"
              style={{ background: "linear-gradient(90deg, transparent, hsl(var(--background)/0.55), transparent)" }}
            />
            <div className="relative flex flex-col sm:flex-row items-start sm:items-center justify-between gap-8">
              <div className="max-w-xl">
                <div className="text-xs tracking-[0.3em] uppercase text-background/55">
                  {language === "ja" ? "全文ケーススタディ" : "Read the full case study"}
                </div>
                <div className="mt-3 text-2xl sm:text-3xl font-semibold tracking-[-0.02em] leading-snug">
                  {language === "ja"
                    ? "JapanPath — LYNTの設計と意思決定の全記録。"
                    : "JapanPath — every product & engineering decision behind LYNT."}
                </div>
              </div>
              <motion.button
                onClick={() => navigate("/project/mediconnect")}
                whileHover={{ scale: 1.04 }}
                whileTap={{ scale: 0.98 }}
                className="group relative inline-flex items-center gap-4 bg-background text-foreground rounded-full pl-7 pr-3 py-3 text-sm sm:text-base font-medium tracking-tight shadow-[0_20px_60px_-20px_rgba(255,255,255,0.35)]"
              >
                <span
                  aria-hidden
                  className="absolute inset-0 rounded-full opacity-0 group-hover:opacity-100 transition-opacity duration-500"
                  style={{
                    background:
                      "linear-gradient(120deg, transparent, hsl(var(--foreground)/0.06), transparent)",
                  }}
                />
                <span className="relative">
                  {language === "ja" ? "ケーススタディを開く" : "Open Case Study"}
                </span>
                <span className="relative w-10 h-10 rounded-full bg-foreground text-background flex items-center justify-center transition-transform duration-300 group-hover:rotate-45">
                  <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                    <path d="M1 11L11 1M11 1H3M11 1V9" stroke="currentColor" strokeWidth="1.5" />
                  </svg>
                </span>
              </motion.button>
            </div>
          </div>
        </motion.div>

      </div>
    </section>
  );
};

export default LyntSection;
